"use server";

import { revalidatePath } from "next/cache";
import {
  createUser,
  deleteUser,
  getAllUsers,
  getUserById,
  updateUser,
  type AdminUser,
  type CreateAdminUserInput,
  type UpdateAdminUserInput,
} from "@/lib/api/admin/user";

export const handleGetAllUsers = async ({
  page,
  limit,
  search,
}: {
  page?: number;
  limit?: number;
  search?: string;
}) => {
  try {
    const result = await getAllUsers({
      page: page && page > 0 ? page : 1,
      limit: limit && limit > 0 ? limit : 10,
      search: search?.trim() || undefined,
    });

    const payload = result.responseData;

    return {
      success: result.isSuccess,
      message: result.responseMessage,
      data: payload.data,
      pagination: payload.meta ?? result.paginationMeta,
    };
  } catch (error: any) {
    return {
      success: false,
      message: error?.response?.data?.responseMessage || error?.message || "Failed to fetch users",
    };
  }
};

export const handleGetUserById = async (id: string) => {
  try {
    const result = await getUserById(id);
    return {
      success: result.isSuccess,
      message: result.responseMessage,
      data: result.responseData,
    };
  } catch (error: any) {
    return {
      success: false,
      message: error?.response?.data?.responseMessage || error?.message || "Failed to fetch user",
    };
  }
};

export const handleCreateUser = async (data: CreateAdminUserInput) => {
  try {
    const result = await createUser(data);

    if (result.isSuccess) {
      revalidatePath("/dashboard/admin/users");
      revalidatePath("/dashboard/admin");
    }

    return {
      success: result.isSuccess,
      message: result.responseMessage,
      data: result.responseData,
    };
  } catch (error: any) {
    return {
      success: false,
      message: error?.response?.data?.responseMessage || error?.message || "Failed to create user",
    };
  }
};

export const handleUpdateUser = async (id: string, data: UpdateAdminUserInput | FormData) => {
  try {
    const result = await updateUser(id, data);

    if (result.isSuccess) {
      revalidatePath("/dashboard/admin/users");
      revalidatePath(`/dashboard/admin/users/${id}`);
    }

    return {
      success: result.isSuccess,
      message: result.responseMessage,
      data: result.responseData,
    };
  } catch (error: any) {
    return {
      success: false,
      message: error?.response?.data?.responseMessage || error?.message || "Failed to update user",
    };
  }
};

export const handleDeleteUser = async (id: string) => {
  try {
    const result = await deleteUser(id);

    if (result.isSuccess) {
      revalidatePath("/dashboard/admin/users");
      revalidatePath("/dashboard/admin");
    }

    return {
      success: result.isSuccess,
      message: result.responseMessage,
    };
  } catch (error: any) {
    return {
      success: false,
      message: error?.response?.data?.responseMessage || error?.message || "Failed to delete user",
    };
  }
};

export interface DuplicateUserGroup {
  key: string;
  keep: AdminUser;
  duplicates: AdminUser[];
}

async function fetchAllUsers(): Promise<
  { success: true; users: AdminUser[] } | { success: false; message: string }
> {
  const limit = 100;
  let page = 1;
  let totalPages = 1;
  const allUsers: AdminUser[] = [];

  do {
    const result = await getAllUsers({ page, limit });

    if (!result.isSuccess) {
      return { success: false, message: result.responseMessage || "Failed to fetch users" };
    }

    allUsers.push(...result.responseData.data);
    totalPages = result.responseData.meta?.totalPages ?? result.paginationMeta?.totalPages ?? 1;
    page += 1;
  } while (page <= totalPages);

  return { success: true, users: allUsers };
}

// fashiome-e2e.test is generated by Playwright's tests/utils/random.ts uniqueEmail().
// example.com is the IETF-reserved placeholder domain (RFC 2606) used by dev/QA scripts
// (e.g. "Cod Timing", "Cod UiTest" accounts) — no real user can register with it.
const TEST_FIXTURE_EMAIL_PATTERN = /@(fashiome-e2e\.test|example\.com)$/i;

function isFixtureUser(user: AdminUser) {
  return TEST_FIXTURE_EMAIL_PATTERN.test(user.email?.trim() ?? "");
}

// Groups users that share an email or a username, keeping the oldest record in each group.
function groupDuplicateUsers(users: AdminUser[]): DuplicateUserGroup[] {
  const parent = new Map<string, string>();

  const find = (id: string): string => {
    if (!parent.has(id)) parent.set(id, id);

    let root = id;
    while (parent.get(root) !== root) root = parent.get(root)!;

    let current = id;
    while (parent.get(current) !== root) {
      const next = parent.get(current)!;
      parent.set(current, root);
      current = next;
    }

    return root;
  };

  const union = (a: string, b: string) => {
    const rootA = find(a);
    const rootB = find(b);
    if (rootA !== rootB) parent.set(rootA, rootB);
  };

  const firstSeenByEmail = new Map<string, string>();
  const firstSeenByUsername = new Map<string, string>();

  for (const user of users) {
    find(user._id);

    const email = user.email?.trim().toLowerCase();
    const username = user.username?.trim().toLowerCase();

    if (email) {
      const existing = firstSeenByEmail.get(email);
      if (existing) union(user._id, existing);
      else firstSeenByEmail.set(email, user._id);
    }

    if (username) {
      const existing = firstSeenByUsername.get(username);
      if (existing) union(user._id, existing);
      else firstSeenByUsername.set(username, user._id);
    }
  }

  const groupsById = new Map<string, AdminUser[]>();
  for (const user of users) {
    const root = find(user._id);
    const group = groupsById.get(root) ?? [];
    group.push(user);
    groupsById.set(root, group);
  }

  return Array.from(groupsById.entries())
    .filter(([, group]) => group.length > 1)
    .map(([key, group]) => {
      const sorted = [...group].sort(
        (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
      );
      const [keep, ...duplicates] = sorted;
      return { key, keep, duplicates };
    });
}

// Finds leftover accounts created by the e2e test suite (tests/test-data/users.ts),
// identified by their generated @fashiome-e2e.test email domain.
export const handleFindTestFixtureUsers = async () => {
  try {
    const fetched = await fetchAllUsers();
    if (!fetched.success) {
      return { success: false, message: fetched.message };
    }

    return { success: true, users: fetched.users.filter(isFixtureUser) };
  } catch (error: any) {
    return {
      success: false,
      message: error?.response?.data?.responseMessage || error?.message || "Failed to find test fixture users",
    };
  }
};

export const handleFindDuplicateUsers = async () => {
  try {
    const fetched = await fetchAllUsers();
    if (!fetched.success) {
      return { success: false, message: fetched.message };
    }

    return { success: true, groups: groupDuplicateUsers(fetched.users) };
  } catch (error: any) {
    return {
      success: false,
      message: error?.response?.data?.responseMessage || error?.message || "Failed to find duplicate users",
    };
  }
};

// Lists real (non-fixture, non-duplicate) users with in-memory search/pagination, since
// the backend has no filter for this. Pass includeAll to fall back to the unfiltered list.
export const handleGetRealUsers = async ({
  page,
  limit,
  search,
  includeAll,
}: {
  page?: number;
  limit?: number;
  search?: string;
  includeAll?: boolean;
}) => {
  try {
    const fetched = await fetchAllUsers();
    if (!fetched.success) {
      return { success: false, message: fetched.message };
    }

    const safePage = page && page > 0 ? page : 1;
    const safeLimit = limit && limit > 0 ? limit : 10;
    const term = search?.trim().toLowerCase();

    let users = fetched.users;
    const fixtureCount = users.filter(isFixtureUser).length;
    const duplicateExtraIds = new Set(
      groupDuplicateUsers(users).flatMap((group) => group.duplicates.map((user) => user._id))
    );

    // An explicit search is a deliberate lookup for a specific record, so it should find
    // fixture/duplicate accounts too rather than silently hiding them from the results.
    if (!includeAll && !term) {
      users = users.filter((user) => !isFixtureUser(user) && !duplicateExtraIds.has(user._id));
    }

    if (term) {
      users = users.filter((user) =>
        [user.firstName, user.lastName, user.email, user.username]
          .filter(Boolean)
          .some((field) => field.toLowerCase().includes(term))
      );
    }

    const total = users.length;
    const totalPages = Math.max(Math.ceil(total / safeLimit), 1);
    const start = (safePage - 1) * safeLimit;
    const data = users.slice(start, start + safeLimit);

    return {
      success: true,
      data,
      pagination: { page: safePage, limit: safeLimit, total, totalPages },
      hiddenCount: fixtureCount + duplicateExtraIds.size,
    };
  } catch (error: any) {
    return {
      success: false,
      message: error?.response?.data?.responseMessage || error?.message || "Failed to fetch users",
    };
  }
};

export const handleBulkDeleteUsers = async (ids: string[]) => {
  const results = await Promise.allSettled(ids.map((id) => deleteUser(id)));

  const failedIds: string[] = [];
  results.forEach((result, index) => {
    if (result.status === "rejected" || !result.value.isSuccess) {
      failedIds.push(ids[index]);
    }
  });

  revalidatePath("/dashboard/admin/users");
  revalidatePath("/dashboard/admin/users/duplicates");
  revalidatePath("/dashboard/admin");

  return {
    success: failedIds.length === 0,
    deletedCount: ids.length - failedIds.length,
    failedIds,
  };
};
